---
title: "Variation de croissance de *Marginopora vertebralis* Quoy & Gaimard, 1830"
output: github_document
lang: "fr"
bibliography: "bibliography/biblio.bib"
---

@2020_DOO ont étudié les effets d'une acidification et d'une augmentation de la température sur *Marginopora vertebralis* Quoy & Gaimard, 1830. Ils ont également étudié en parallèlle ces effets lorsque M. vertebralis est associé à l'un de ces hotes *Laurencia intricata* J.V.Lamouroux, 1813.

Les auteurs ont publié les données pour réaliser cette étude [@2020_DOO_data]. Vous utiliserez une partie de ces données pour appliquer l'analyse de variance à un facteur et le test de Kruskal-Wallis. Les données mises à disposition par les auteurs de l'article se trouvent dans le dossier `data/raw/`.

# Objectifs

Ce projet est individuel et cadré. Il permet de démontrer que vous avez acquis les compétences suivantes :

-   représenter graphiquement de la manière la plus appropriée les données à comparer avec une ANOVA
-   être capable de formuler les hypothèses de l'ANOVA et du test de Kruskal-Wallis
-   Pouvoir réaliser une interprétation des tests sur des données biologiques

# Consignes

Complétez le document `vertebralis.Rmd`. Vous allez explorer la croissance du Formaminifère *M. vertebralis* en condition de stress en présence ou non de son hôte *L. intricata*, une algue.

N'oubliez pas de "knitter" le document en HTML à la fin du travail pour vérifier que tout fonctionne bien, et corrigez les erreurs éventuelles rencontrées à ce stade avant de clôturer votre travail. Vérifiez également que votre dernier commit a bien été pushé sur GitHub avant la deadline.

# Bibliographie
