---
title: "___"
author: "___"
date: "`r Sys.Date()`"
output: html_document
---

# Introduction

<!--% Rédigez une introduction en 2 à 4 phrases sur *Marginopora vertebralis* Quoy & Gaimard, 1830 et sur *Laurencia intricata* J.V.Lamouroux, 1813.-->

# Analyses

```{r setup}
SciViews::R("infer", "model", lang = "fr")
```

<!--% Importez le tableau growth.rds depuis le dossier data. -->

```{r import}
growth <- ___
skimr::skim(growth)
# Ne modifiez pas ci-dessous
write$rds(growth, here::here("tests", "growth.rds"), compress = "xz")
```

## Variation de la croissance de *M. vertebralis* en condition de stress

<!--% Sélectionnez uniquement les observations réalisées sur *M. vertebralis* seul. -->

```{r filter1}
growth1 <- ___
# Ne modifiez pas ci-dessous
write$rds(growth1, here::here("tests", "growth1.rds"), compress = "xz")
```

<!--% Réalisez un tableau résumant l'expérience avec des descripteurs numériques pertinents. -->

```{r descri1}
tab1 <- ___
tab1
# Ne modifiez pas ci-dessous
write$rds(tab1, here::here("tests", "tab1.rds"), compress = "xz")
```

<!--% Réalisez un nuage de points pertinent qui présente la moyenne et l'erreur standard afin d'illustrer la situation. -->

```{r plot1}
p1 <- ___
p1
# Ne modifiez pas ci-dessous
write$rds(p1, here::here("tests", "p1.rds"), compress = "xz")
```

<!--% Décrivez le graphique et le tableau réalisé en 3 à 4 phrases. -->

<!--% Réalisez l'ANOVA à un facteur en utilisant la variable `temp_ph` pour les groupes (qui est la combinaison de la variable `temp` et de la variable `ph`). -->

```{r anova1}
anova1 <- ___
anova(___)  
# Ne modifiez pas ci-dessous
write$rds(anova1, here::here("tests", "anova1.rds"), compress = "xz")
```

<!--% Vérifiez les conditions d'application de l'ANOVA à un facteur. -->

```{r appli1}
# Normalité des résidus
___
# Homoscédasticité
homo <- ___
homo
# Ne modifiez pas ci-dessous
write$rds(homo, here::here("tests", "homo1.rds"), compress = "xz")
```

<!--% Réalisez le test de comparaison multiple, si cela est justifié. Sinon laissez ce chunk vide. -->

```{r multcomp1}

```

<!--% Interprétez en 5 lignes votre anova à 1 facteur. Soyez complet ! Traitez de la description statistique et biologique. N'oubliez pas les conditions d'application du test..-->

## Variation de la croissance de *M. vertebralis* en présence de *L. intricata*

<!--% Sélectionnez uniquement les observations réalisées sur *M. vertebralis* associé à *L. intricata*. -->

```{r filter2}
growth2 <- ___
# Ne modifiez pas ci-dessous
write$rds(growth2, here::here("tests", "growth2.rds"), compress = "xz")
```

<!--% Réalisez un tableau résumant l'expérience avec des descripteurs numériques pertinents. -->

```{r descri2}
tab2 <- ___
tab2
# Ne modifiez pas ci-dessous
write$rds(tab2, here::here("tests", "tab2.rds"), compress = "xz")
```

<!--% Réalisez un nuage de points pertinent qui comprend la moyenne et l'erreur standard afin d'illustrer la situation. -->

```{r plot2}
p2 <- ___
p2
# Ne modifiez pas ci-dessous
write$rds(p2, here::here("tests", "p2.rds"), compress = "xz")
```

<!--% Décrivez le graphique réalisé en 2 à 3 phrases. -->

<!--% Réalisez l'ANOVA à un facteur en utilisant la variable `temp_ph` pour le regroupement (combinaison de la variable `temp` et de la variable `ph`). -->

```{r anova2}
anova2 <- ___
anova(___)  
# Ne modifiez pas ci-dessous
write$rds(anova2, here::here("tests", "anova2.rds"), compress = "xz")
```

<!--% Vérifiez les conditions d'application de l'ANOVA à un facteur. -->

```{r appli2}
# Normalité des résidus
___
# Homoscédasticité
homo2 <- ___
homo2
# Ne modifiez pas ci-dessous
write$rds(homo2, here::here("tests", "homo2.rds"), compress = "xz")
```

<!--% Réalisez le test de comparaison multiple, si cela est justifié. Sinon laissez ce chunk vide. -->

```{r multcomp2}

```

<!--% Interprétez en 5 lignes votre ANOVA à 1 facteur. Soyez complet ! Traitez de la description statistique et biologique. N'oubliez pas les conditions d'application du test. -->

<!--% BONUS : Comparez votre graphique réalisé dans le chunk `descri1` par rapport à celui proposé par les auteurs de la publication en 2 à 3 phrases. -->
